apiVersion: v1
kind: Secret
metadata:
  name: appointment-secret
  namespace: default
  labels:
    app: appointment-service
type: Opaque
stringData:
  PORT: "3004"
  MONGO_URI: "mongodb+srv://whitedeviltest0940:Qwer11223344@cluster0.bqkmeme.mongodb.net/carenet_db?appName=Cluster0"
  JWT_SECRET: "ufjkrm*$&+!=JfldsJKLfesadk421!@$45922dakjfsafdafa38fjkdjasKLJKFAF"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  DOCTOR_SERVICE_URL: "http://doctor-service:3003"
  PATIENT_SERVICE_URL: "http://patient-service:3002"
