apiVersion: v1
kind: Secret
metadata:
  name: doctor-secret
  namespace: default
  labels:
    app: doctor-service
type: Opaque
stringData:
  PORT: "3003"
  MONGO_URI: "mongodb+srv://whitedeviltest0940:Qwer11223344@cluster0.bqkmeme.mongodb.net/carenet_db?appName=Cluster0"
  JWT_SECRET: "ufjkrm*$&+!=JfldsJKLfesadk421!@$45922dakjfsafdafa38fjkdjasKLJKFAF"
