apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
  labels:
    app: doctor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          image: carenet-doctor-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: doctor-secret
                  key: PORT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: doctor-secret
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: doctor-secret
                  key: JWT_SECRET
