apiVersion: v1
kind: Secret
metadata:
  name: doctor-secret
  namespace: default
  labels:
    app: doctor-service
type: Opaque
stringData:
  PORT: "5001"
  MONGO_URI: "mongodb://mongodb:27017/healthcare_doctors"
  JWT_SECRET: "change-this-doctor-jwt-secret"
