apiVersion: v1
kind: Secret
metadata:
  name: patient-secret
type: Opaque
stringData:
  JWT_SECRET: "ufjkrm*$&+!=JfldsJKLfesadk421!@$45922dakjfsafdafa38fjkdjasKLJKFAF"
  MONGO_URI: "mongodb+srv://whitedeviltest0940:Qwer11223344@cluster0.bqkmeme.mongodb.net/patient_db?appName=Cluster0"
