apiVersion: apps/v1
kind: Deployment
metadata:
  name: symptom-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symptom-service
  template:
    metadata:
      labels:
        app: symptom-service
    spec:
      containers:
        - name: symptom-service
          image: symptom-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3008
          env:
            - name: PORT
              value: "3008"
            - name: APPOINTMENT_SERVICE_URL
              value: "http://appointment-service:3004"
            - name: GEMINI_API_KEY
              value: "AIzaSyBZTyREXEEGmRARDEb5WxwcQGwUxhPsTyI"
              # valueFrom:
              #   secretKeyRef:
              #     name: symptom-secret
              #     key: GEMINI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: symptom-service
spec:
  selector:
    app: symptom-service
  ports:
    - port: 3008
      targetPort: 3008
