apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: telemedicine-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3007
          env:
            - name: PORT
              value: "3007"
            - name: MONGO_URI
              value: "mongodb+srv://whitedeviltest0940:Qwer11223344@cluster0.bqkmeme.mongodb.net/carenet_db?appName=Cluster0"
            - name: JWT_SECRET
              value: "carenet_secret"
            - name: APPOINTMENT_SERVICE_URL
              value: "http://appointment-service:3004"
            - name: JITSI_DOMAIN
              value: "8x8.vc"
            - name: JITSI_ENFORCE_JWT
              value: "false"
          livenessProbe:
            httpGet:
              path: /health
              port: 3007
            initialDelaySeconds: 20
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 3007
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
spec:
  selector:
    app: telemedicine-service
  ports:
    - protocol: TCP
      port: 3007
      targetPort: 3007
  type: ClusterIP